.PHONY: validate test baseline-check check

validate:
	PYTHONPATH=src python3 -m agent_enhance validate .

test:
	PYTHONPATH=src python3 -m unittest discover -s tests -v

baseline-check:
	python3 scripts/validate_baseline_matrix.py
	python3 scripts/validate_source_results.py
	python3 scripts/validate_baseline_evidence_v2.py
	python3 scripts/validate_baseline_evidence_v3.py
	python3 scripts/validate_foundation_results.py
	python3 scripts/validate_model_retention_policy_v2.py
	python3 scripts/validate_baseline_model_ownership_ledger.py
	python3 scripts/validate_baseline_model_ownership_ledger_v2.py
	python3 scripts/validate_model_cleanup_controller.py
	python3 scripts/validate_model_cleanup_controller_v2.py
	python3 scripts/validate_model_cleanup_control_package_v2.py
	python3 scripts/validate_model_cleanup_controller_v3.py
	python3 scripts/validate_model_cleanup_control_package_prefreeze_v3.py
	python3 scripts/validate_model_cleanup_control_package_v3.py
	python3 scripts/validate_recent_method_reproduction_roadmap_v2.py
	python3 scripts/validate_recent_method_reproduction_roadmap_v3.py
	python3 scripts/validate_recent_method_execution_coverage.py
	python3 scripts/validate_recent_method_model_retirement_coverage.py
	python3 scripts/validate_wma_table_bundle_v2.py --require-no-admitted-results
	python3 scripts/validate_wma_table_bundle_v3.py --require-no-admitted-results
	python3 scripts/validate_wma_wave3_source_audit.py
	python3 scripts/validate_wma_wave3_adapter_and_models.py
	python3 scripts/validate_wma_wave3_execution_source_audit.py
	python3 scripts/validate_wma_wave3_environment_and_lifecycle.py
	python3 scripts/validate_wma_wave4_tierb_source_readiness.py
	python3 scripts/validate_wma_wave5_structmem_source_readiness.py
	python3 scripts/validate_hf_model_materialization_successors.py
	python3 scripts/validate_wma_postwave_release_sequence.py
	python3 scripts/validate_wma_postwave_release_sequence_v2.py
	python3 scripts/validate_wma_postwave_release_sequence_v3.py
	python3 scripts/validate_post_wma_cross_track_completion.py
	python3 scripts/validate_causal_locomo_real_model_integrity_prefreeze.py
	python3 scripts/validate_causal_locomo_five_method_overlay_proposal.py
	python3 scripts/validate_causal_locomo_endpoint_client_proposal.py
	python3 scripts/validate_causal_locomo_raw_writer_proposal.py
	python3 scripts/validate_causal_locomo_lifecycle_controller_proposal.py
	python3 scripts/validate_causal_locomo_offline_evaluator_proposal.py
	python3 scripts/validate_causal_locomo_main_table_proposal.py
	python3 scripts/validate_causal_locomo_table_projection_proposal.py
	python3 scripts/validate_causal_locomo_paired_analysis_proposal.py
	python3 scripts/validate_memgallery_data_prefetch_manifest.py
	python3 scripts/validate_memgallery_data_materialization_prefreeze.py
	python3 scripts/validate_memgallery_data_control_package.py
	python3 scripts/validate_memgallery_data_negative_gate.py
	python3 scripts/validate_memgallery_data_integrity_prefreeze.py
	python3 scripts/validate_memgallery_data_integrity_control_package.py
	python3 scripts/validate_memgallery_run_reconciliation_prefreeze.py
	python3 scripts/validate_memgallery_run_reconciliation_control_package.py
	python3 scripts/validate_memgallery_static_model_prefetch_manifest.py
	python3 scripts/validate_memgallery_static_method_entry_prefreeze.py
	python3 scripts/validate_memgallery_siglip2_prefetch_manifest.py
	python3 scripts/validate_memgallery_siglip2_materialization_prefreeze.py
	python3 scripts/validate_memgallery_siglip2_materialization_gate_prefreeze.py
	python3 scripts/validate_memgallery_siglip2_gate_control_package.py
	python3 scripts/validate_memgallery_control_core_prefreeze.py
	python3 scripts/validate_memgallery_control_adapter_prefreeze.py
	python3 scripts/validate_memgallery_dataset_projection_loader_prefreeze.py
	python3 scripts/validate_memgallery_answer_contract_prefreeze.py
	python3 scripts/validate_memgallery_endpoint_client_prefreeze.py
	python3 scripts/validate_memgallery_control_runner_prefreeze.py
	python3 scripts/validate_memgallery_raw_run_writer_prefreeze.py
	python3 scripts/validate_memgallery_lifecycle_controller_prefreeze.py
	python3 scripts/validate_wma_local_result_admission.py
	python3 scripts/validate_wma_wave1_recovery2.py
	python3 scripts/validate_wma_wave1_release_gate_prefreeze.py
	python3 scripts/validate_wma_wave1_recovery2_closure.py
	python3 scripts/validate_wma_wave1_recovery2_result_admission.py
	python3 scripts/validate_wma_wave1_failure_history_archive.py
	python3 scripts/validate_wma_wave2_runner_implementation.py

check: validate test baseline-check
