#!/usr/bin/env python3
"""Recovery1: compare Hindsight uv exports after exact header removal."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


sys.path.insert(0, str(Path(__file__).resolve().parent))
import export_hindsight_uv_lock as v1  # noqa: E402


HEADER_LINE = b"# This file was autogenerated by uv via the following command:\n"
COMMAND_PREFIX = b"#    uv export "
EXPECTED_BODY_BYTES = 256_006
EXPECTED_BODY_SHA256 = "6f0836431e1a0ba74bdc92732ffb0a81a1c72691bdab2bc3fba43c4a1e3716c6"
EXPECTED_REQUIREMENT_HEAD_COUNT = 208


def normalized_body(payload: bytes) -> bytes:
    lines = payload.splitlines(keepends=True)
    if len(lines) < 3 or lines[0] != HEADER_LINE:
        raise RuntimeError("unexpected uv generator header line")
    if not lines[1].startswith(COMMAND_PREFIX) or not lines[1].endswith(b"\n"):
        raise RuntimeError("unexpected uv generator command line")
    body = b"".join(lines[2:])
    if not body:
        raise RuntimeError("empty normalized dependency body")
    return body


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--uv", type=Path, required=True)
    parser.add_argument("--python", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--evidence-root", type=Path, required=True)
    args = parser.parse_args()
    uv = v1.validate_project_path(args.uv, ("AgentEnhance", "tools"))
    source = v1.validate_project_path(args.source, ("AgentEnhance", "third_party"))
    evidence_root = v1.validate_project_path(args.evidence_root, ("AgentEnhance", "runs"))
    python = args.python.resolve()
    if not python.is_absolute() or python.is_symlink() or not python.is_file():
        raise SystemExit("Python interpreter must be an absolute regular file")
    if evidence_root.exists():
        raise SystemExit("refusing existing recovery lock-export evidence root")
    evidence_root.mkdir(parents=True)
    started_at = v1.now()
    try:
        if v1.sha256_file(uv) != v1.UV_SHA256:
            raise RuntimeError("uv binary hash mismatch")
        uv_version = subprocess.check_output([str(uv), "--version"], text=True).strip()
        if uv_version != v1.UV_VERSION_OUTPUT:
            raise RuntimeError(f"uv version mismatch: {uv_version}")
        if v1.sha256_file(python) != v1.PYTHON_SHA256:
            raise RuntimeError("Python interpreter hash mismatch")
        python_version = subprocess.check_output(
            [str(python), "-c", "import sys; print(sys.version)"], text=True
        ).strip()
        if not python_version.startswith(v1.PYTHON_VERSION_PREFIX):
            raise RuntimeError(f"Python version mismatch: {python_version}")
        revision = subprocess.check_output(
            ["git", "-C", str(source), "rev-parse", "HEAD"], text=True
        ).strip()
        if revision != v1.SOURCE_REVISION:
            raise RuntimeError("Hindsight source revision mismatch")
        if subprocess.check_output(
            ["git", "-C", str(source), "status", "--porcelain"], text=True
        ).strip():
            raise RuntimeError("Hindsight source is dirty")
        lock = source / "uv.lock"
        if lock.stat().st_size != v1.LOCK_BYTES or v1.sha256_file(lock) != v1.LOCK_SHA256:
            raise RuntimeError("Hindsight uv.lock identity mismatch")
        lock_before = v1.sha256_file(lock)
        raw_outputs = []
        environment = os.environ.copy()
        environment["UV_NO_PROGRESS"] = "1"
        for label in ("a", "b"):
            output = evidence_root / f"hindsight-all-requirements-{label}.raw.txt"
            completed = subprocess.run(
                v1.export_command(uv, python, output),
                cwd=source,
                env=environment,
                text=True,
                capture_output=True,
                check=True,
            )
            (evidence_root / f"export-{label}.stdout.log").write_text(
                completed.stdout, encoding="utf-8"
            )
            (evidence_root / f"export-{label}.stderr.log").write_text(
                completed.stderr, encoding="utf-8"
            )
            raw_outputs.append(output)
        lock_after = v1.sha256_file(lock)
        if lock_after != lock_before:
            raise RuntimeError("uv.lock changed during frozen export")
        if subprocess.check_output(
            ["git", "-C", str(source), "status", "--porcelain"], text=True
        ).strip():
            raise RuntimeError("source changed during frozen export")
        bodies = [normalized_body(path.read_bytes()) for path in raw_outputs]
        if bodies[0] != bodies[1]:
            raise RuntimeError("normalized dependency bodies are not byte-identical")
        canonical = evidence_root / "hindsight-all-requirements.txt"
        canonical.write_bytes(bodies[0])
        if (
            canonical.stat().st_size != EXPECTED_BODY_BYTES
            or v1.sha256_file(canonical) != EXPECTED_BODY_SHA256
        ):
            raise RuntimeError("canonical dependency body identity mismatch")
        text = canonical.read_text(encoding="utf-8")
        prohibited = ("-e ", "file://", str(source), "hindsight-all @", "hindsight-api-slim @")
        if any(token in text for token in prohibited):
            raise RuntimeError("canonical export contains a prohibited workspace reference")
        if not all(token in text for token in v1.REQUIRED_PACKAGES):
            raise RuntimeError("canonical export is missing a required runtime dependency")
        heads = v1.requirement_heads(text)
        if len(heads) != EXPECTED_REQUIREMENT_HEAD_COUNT:
            raise RuntimeError("canonical requirement cardinality mismatch")
        result = {
            "schema_version": "agentenhance.hindsight_uv_lock_export.v2",
            "status": "TERMINAL_ACCEPTED",
            "recovery": "recovery1_exact_uv_header_removal",
            "source_revision": revision,
            "source": str(source),
            "uv_lock_bytes": lock.stat().st_size,
            "uv_lock_sha256_before": lock_before,
            "uv_lock_sha256_after": lock_after,
            "uv": str(uv),
            "uv_sha256": v1.sha256_file(uv),
            "uv_version_output": uv_version,
            "python": str(python),
            "python_sha256": v1.sha256_file(python),
            "python_version": python_version,
            "started_at": started_at,
            "finished_at": v1.now(),
            "normalization": "remove exactly two validated uv autogenerated header lines; preserve every dependency-body byte",
            "raw_exports": [
                {"path": str(path), "bytes": path.stat().st_size, "sha256": v1.sha256_file(path)}
                for path in raw_outputs
            ],
            "canonical_export": {
                "path": str(canonical),
                "bytes": canonical.stat().st_size,
                "sha256": v1.sha256_file(canonical),
            },
            "normalized_bodies_byte_identical": True,
            "requirement_head_count": len(heads),
            "requirement_heads": heads,
            "network_enabled": False,
            "dependency_install_performed": False,
        }
        record = evidence_root / "lock-export.json"
        record.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        evidence_files = [record, canonical, *raw_outputs]
        evidence_files.extend(sorted(evidence_root.glob("export-*.log")))
        inventory = evidence_root / "EVIDENCE_SHA256SUMS"
        inventory.write_text(
            "".join(f"{v1.sha256_file(path)}  {path}\n" for path in evidence_files),
            encoding="utf-8",
        )
        (evidence_root / "TERMINAL_ACCEPTED").touch()
        print(json.dumps({"status": result["status"], "requirement_head_count": len(heads), "canonical_bytes": canonical.stat().st_size, "canonical_sha256": v1.sha256_file(canonical)}, sort_keys=True))
        return 0
    except Exception as exc:
        failure = {
            "schema_version": "agentenhance.hindsight_uv_lock_export_failure.v2",
            "status": "TERMINAL_REJECTED",
            "recovery": "recovery1_exact_uv_header_removal",
            "started_at": started_at,
            "finished_at": v1.now(),
            "error_type": type(exc).__name__,
            "error": str(exc),
            "cleanup_authorized": False,
        }
        record = evidence_root / "lock-export-failure.json"
        record.write_text(json.dumps(failure, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        (evidence_root / "EVIDENCE_SHA256SUMS").write_text(
            f"{v1.sha256_file(record)}  {record}\n", encoding="utf-8"
        )
        (evidence_root / "TERMINAL_REJECTED").touch()
        print(json.dumps(failure, sort_keys=True), file=sys.stderr)
        return 5


if __name__ == "__main__":
    raise SystemExit(main())
